export const MAX_CAMERA_WATCHLISTS = 50;
export const MAX_DETECTION_CLASSES = 80;
export const MAX_DETECTION_CLASS_LENGTH = 50;
export const MAX_CAMERA_NAME_LENGTH = 100;
export const MAX_SOURCE_URL_LENGTH = 500;
export const MAX_LOCATION_LENGTH = 200;
export const MAX_CREDENTIAL_USERNAME_LENGTH = 100;
export const MAX_CREDENTIAL_PASSWORD_LENGTH = 200;
